### PR TITLE
use ListPeerChannels 

### PR DESCRIPTION
**Pull request by YusukeShimizu**
CLN 24.05 removed channels list from ListPeers response.
The listpeers command in the clightning package to use the listpeerchannels function instead of listpeers.

fixes https://github.com/ElementsProject/peerswap/pull/304#issuecomment-2326310507

### CODE REVIEW

**Comment by grubles** [comment]
I get the same message in my debug.log whether running master or this PR:

```
2024-09-11T17:23:36.596Z **BROKEN** plugin-topology: DEPRECATED API USED: listchannels.include_private by \"12/cln:listchannels#130\"
```

**Comment by Impa10r** [comment]
this is a bug in CLN 23.08

**Comment by wtogami** [comment]
Running master branch with d51fa0a62b4ef32b4c076a62aadc956103d94361 locally merged for the past two days.

```
2024-09-15T00:47:25.078Z DEBUG   plugin-peerswap: 
2024-09-15T00:47:25.078Z DEBUG   plugin-peerswap:  msghandler err: message type not in range
2024-09-15T00:47:25.078Z DEBUG   plugin-peerswap: 
2024-09-15T00:47:25.078Z DEBUG   plugin-peerswap:  msghandler err: message type not in range
```

Unclear where this is coming from. It happened only twice so far.

**Comment by grubles** [comment]
@wtogami Those errors have occurred for me since at least April, according to my debug.log. It looks like the `chanbackup` plugin prints a message right before those errors each time. Examples:

```
2024-08-05T21:09:48.500Z DEBUG   plugin-chanbackup: datastore succeeded for Saving latestscb           
2024-08-05T21:09:48.503Z DEBUG   plugin-peerswap:                                                      
2024-08-05T21:09:48.503Z DEBUG   plugin-peerswap:  msghandler err: message type not in range           
2024-08-05T21:09:48.503Z DEBUG   plugin-peerswap:                                                      
2024-08-05T21:09:48.503Z DEBUG   plugin-peerswap:  msghandler err: message type not in range  
```


```
2024-09-10T17:08:42.250Z DEBUG   plugin-chanbackup: Peer sent bad custom message for chanbackup!       
2024-09-10T17:08:42.253Z DEBUG   plugin-peerswap:                                                      
2024-09-10T17:08:42.253Z DEBUG   plugin-peerswap:  msghandler err: message type not in range           
2024-09-10T17:08:42.253Z DEBUG   plugin-peerswap:                                                      
2024-09-10T17:08:42.253Z DEBUG   plugin-peerswap:  msghandler err: message type not in range 
```

**Comment by Impa10r** [comment]
> @wtogami Those errors have occurred for me since at least April

https://github.com/ElementsProject/peerswap/issues/305

**Comment by YusukeShimizu** [comment]
I am going to close this pr because it is not serving its purpose, but please let me know if there are any problems.

**Comment by YusukeShimizu** [comment]
I wll summarize the situation:

The `plugin-topology: DEPRECATED API USED` https://github.com/ElementsProject/peerswap/pull/314#issuecomment-2344275205 will not be fixed by the changes in this Pull Request. It seems that a fix is [planned on the core lightning side](https://discord.com/channels/899980449231814676/899989729183940629/1283054236778758166).

While the `channels` field in `ListPeers` will be removed in version 23.05(https://github.com/rustyrussell/lightning/commit/857a55cb45d03b6ce2b3ea8f6731eb3460a828f4) , my understanding is that the `peerswap-listpeers` does not uses the `channels` field.

`msghandler err: message type not in range` https://github.com/ElementsProject/peerswap/pull/314#issuecomment-2351258773 is addressed by https://github.com/ElementsProject/peerswap/pull/315.

**Comment by YusukeShimizu** [comment]
https://github.com/ElementsProject/lightning/issues/7652 could be the cause.
`peerswap-listpeers` has a dependency on `listchannels`.

If that's the cause, no fix is needed for peerswap, and it should be resolved by updating the cln version.

**Comment by wtogami** [comment]
https://github.com/ElementsProject/lightning/commits/release-24.08.1/
Confirmed the deprecation warning is fixed in upcoming CLN v24.08.1. Closing.

**Pull request closed without merging**
