### PR TITLE
Updated default regtest port to the correct port 18443.

### PR DESCRIPTION
**Pull request by cmdruid**
Updated default regtest port to the correct port 18443.

### CODE REVIEW

**Comment by wtogami** [comment]
image

You put the description on the second line of the commit message. We don't need to know "Update filename" and especially not in the first line that becomes the visible commit description.

Try `git commit --amend` to edit the previous commit message. Then `git push YOURREMOTENAME YOURBRANCHNAME --force` to replace the commit in your github.com hosted branch. This allows you to update commits without closing and opening a new pull requests. But **be very careful** with `--force` because you can mess things up if you don't know what you're doing.

**Review by wtogami — CHANGES_REQUESTED** [review]
Put actual description in the first line of your commit message then `git push --force` to replace rather than open a new pull request.

**Comment by cmdruid** [comment]
My apologies. The `--force` flag did indeed mess things up previously, so instead I just made a new PR from Github. However Github has a character limit for comments and forces me to use a 'description'. I amended the comment.

**Comment by grubles** [comment]
ACK e045333f352500992a82bec1aae8cbb3b460baf1

**Review by wtogami — APPROVED** [review]

**Pull request merged**
