### PR TITLE
Rework LND Watchers and Listeners

### LINKED ISSUE #108: Switch to polling for LND RPC
For the entire existence of LND PeerSwap we wasted a lot of cycles while attempting to debug stuff only to find we were experiencing intermittent unrelated failures where grpc is yet again flaky. It is supposed to recover on its own but it doesn't. We could try to somehow fix grpc connection recovery but I think it isn't worth it because there is no solution to #57 where the underlying restarted LND had forgotten subscriptions. We also heard from another major app that they always poll LND with new connections and that had been reliable for them.

"Switch to polling" is the general idea but this adds new complications.

* If every RPC is a new connection then you need to recheck each time if LND is synced. Maybe that's fast enough so it's OK for now? Let's find out.
* But some things we were relying upon are not a simple query but rather subscriptions.
* Maybe both of the above would be helped by making LND RPC calls **indirect** via an event queue. The event queue is another thread acting as a RPC proxy where only it interfaces with LND RPC. It monitors for temporary LND errors or a LND restart. In those cases it either blocks to wait for possible recovery, or passes the raw error messages to the calling function. The event queue could also implement a "subscription" model that is remembered only internally within PeerSwap runtime memory but it actually uses polling to check if the subscribed event had happened.

I don't know what approach would be easiest to implement. Slow and simple might be good enough for now. The event queue might be more efficient in the long-term but adds complexity that might not be worth it.

I wonder if all those extra polling connections and frequent "are you ready?" calls would spam up LND's logs?

### PR DESCRIPTION
**Pull request by nepet**
As stated in #108 we had some trouble in the case that lnd dropped the grpc connection. This could be either because lnd got offline or because of a flaky grpc connection. #111 Was the first part of two, trying to solve our connection issues.
This is the second part that is a rework of all the lnd subscriptions we use right now. The pr also adds tests to the listeners and watchers to ensure that they resubscribe and continue work after lnd was killed and restarted.

This resolves #108

### CODE REVIEW

**Comment by nepet** [comment]
For testers: please also check if this resolves #57

**Comment by kornpow** [comment]
Unfortunately while restarting LND midswap it appears it didnt recover for me.

```
# STOPPED LND
0, rpc error: code = Unknown desc = chain notifier shutting down
2022/08/21 12:11:24 [INFO] [PeerListener]: Stream closed
2022/08/21 12:11:24 [INFO] [MsgListener]: Stream closed with err: rpc error: code = Internal desc = server closed the stream without sending trailers
2022/08/21 12:20:46 [DEBUG] [FSM] event:id: a2ae5be03c914776cc8e95b722bf279fb9b9925480c0f22a028759a398576530, Event_OnTimeout on State_SwapOutSender_AwaitTxConfirmation


#RESTARTED DAEMON
2022/08/21 12:21:17 [INFO] [Swap:a2ae5be03c914776cc8e95b722bf279fb9b9925480c0f22a028759a398576530]: Recovering from state State_SwapOutSender_AwaitTxConfirmation
2022/08/21 12:21:17 [DEBUG] [TxWatcher] Swap: a2ae5be03c914776cc8e95b722bf279fb9b9925480c0f22a028759a398576530: Add new confirmation watcher for tx 7e908a27d254c9fb08add2dfec17d36d016b6e9d698d90a455edaa40f1b46ef0, awaiting 3 confirmations
2022/08/21 12:21:17 [DEBUG] Await confirmation for tx with id: 7e908a27d254c9fb08add2dfec17d36d016b6e9d698d90a455edaa40f1b46ef0 on swap a2ae5be03c914776cc8e95b722bf279fb9b9925480c0f22a028759a398576530
2022/08/21 12:21:17 [INFO] [MsgListener]: Start listening for custom messages
2022/08/21 12:21:17 [INFO] peerswapd grpc listening on localhost:42069
2022/08/21 12:21:17 [INFO] peerswapd rest listening on localhost:42070
2022/08/21 12:21:18 [DEBUG] [MsgListener]: Received custom message type a463 from 02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f
2022/08/21 12:21:18 [DEBUG] [Messenger] From: 02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f got msgtype: a463 payload: {"version":0,"assets":["lbtc","btc"],"peer_allowed":true}
2022/08/21 12:21:29 [DEBUG] [PeerListener]: PEER_ONLINE 025222e79bf200873e16260af2b67e409f8740082aa25c5da145e42fe444921c9f
2022/08/21 12:21:30 [DEBUG] poll_service: could not send poll msg: rpc error: code = Unknown desc = peer 025222e79bf200873e16260af2b67e409f8740082aa25c5da145e42fe444921c9f disconnected
2022/08/21 12:21:30 [DEBUG] [PeerListener]: PEER_OFFLINE 025222e79bf200873e16260af2b67e409f8740082aa25c5da145e42fe444921c9f
```

**Comment by grubles** [comment]
I ran into the CPU usage issue reported in #57 when stopping LND while peerswapd is running.

**Comment by nepet** [comment]
@kornpow can it be that you gracefully shut down lnd? If this is the case, I guess the expected behavior for peerswap is to also shut down? Or should we keep peerswap running in this case?

The reconnection should happen if lnd exits unexpected (with a `kill` for example)

@grubles Thanks for noting, wondering where this is coming from. Is it one of the same logs as in #57 e.g. `error listening on peer events rpc error: code = Unknown desc = waiting to start, RPC services not available`?

**Comment by wtogami** [comment]
> @kornpow can it be that you gracefully shut down lnd? If this is the case, I guess the expected behavior for peerswap is to also shut down? Or should we keep peerswap running in this case?
> The reconnection should happen if lnd exits unexpected (with a kill for example)

The entire point of adding the this was to help it to recover on its own especially mid-swap?
Why should this be different?

**Comment by nepet** [comment]
Okay, I added retry on errors of type `io.EOF` which indicates that a stream was closed by the server which lnd does in some cases of graceful shutdown. 
Also I added tests on reconnect when lnd was shutdown gracefully

**Comment by kornpow** [comment]
Awesome Ill give it a try again today. I have it just connected to my mainnet Voltage LND node so it should be a fairly normal and safe shutdown flow.

**Comment by kornpow** [comment]
Doesn't appear to be fixed for me with latest pushes. Been waiting 7 minutes since LND restarted.
```
2022/08/23 10:28:49 [INFO] [TxWatcher] Swap: d4bd509043f5040a50a3135f3117214e2a9b0179e5f1ae53d84ec112e57c3dff: Failed waiting for tx watcher for tx 09296d722583ec330dac10ac50b9effddaf6964e48dc56118efee8a83a435e36, rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
2022/08/23 10:28:49 [INFO] [PeerListener]: Stream closed with err: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
```

**Comment by nepet** [comment]
Next try, the following changed:
- I switched to a constant back-off strategy to improve the testing.
- Added the possibility to the middleware to always retry (except client side context cancellation).
- Added logs and a logger to the middleware.
- Made some logs more descriptive.

**Comment by kornpow** [comment]
Success! Was able to restart LND midswap and have it recover with restarting `peerswapd`. The additional logging was good... when it was relevant.
```
2022/08/24 14:47:19 [DEBUG] [grpc_conn]: grpc_retry attempt: 3, backoff for 30s
...
2022/08/24 14:47:23 [DEBUG] [grpc_conn]: grpc_retry attempt: 2, got err: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
2022/08/24 14:47:23 [DEBUG] [grpc_conn]: grpc_retry attempt: 3, backoff for 30s
...
...
2022/08/24 14:47:53 [DEBUG] [grpc_conn]: grpc_retry attempt: 3, got err: rpc error: code = Unknown desc = wallet locked, unlock it to enable full RPC access
2022/08/24 14:47:53 [DEBUG] [grpc_conn]: grpc_retry attempt: 4, backoff for 30s
````

However, once LND reconnected I got some intense spam about peers!
```
2022/08/24 15:33:58 [DEBUG] [grpc_conn]: grpc_retry attempt: 83, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:33:58 [DEBUG] [grpc_conn]: grpc_retry attempt: 84, backoff for 30s
2022/08/24 15:33:58 [DEBUG] [grpc_conn]: grpc_retry attempt: 86, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:33:58 [DEBUG] [grpc_conn]: grpc_retry attempt: 87, backoff for 30s
2022/08/24 15:33:59 [DEBUG] [grpc_conn]: grpc_retry attempt: 74, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:33:59 [DEBUG] [grpc_conn]: grpc_retry attempt: 75, backoff for 30s
2022/08/24 15:34:09 [DEBUG] [grpc_conn]: grpc_retry attempt: 34, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:34:09 [DEBUG] [grpc_conn]: grpc_retry attempt: 35, backoff for 30s
2022/08/24 15:34:11 [DEBUG] [grpc_conn]: grpc_retry attempt: 86, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:34:11 [DEBUG] [grpc_conn]: grpc_retry attempt: 87, backoff for 30s
2022/08/24 15:34:14 [DEBUG] [grpc_conn]: grpc_retry attempt: 85, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:34:14 [DEBUG] [grpc_conn]: grpc_retry attempt: 86, backoff for 30s
2022/08/24 15:34:14 [DEBUG] [grpc_conn]: grpc_retry attempt: 87, got err: rpc error: code = NotFound desc = peer is not connected
2022/08/24 15:34:14 [DEBUG] [grpc_conn]: grpc_retry attempt: 88, backoff for 30s
2022/08/24 15:38:24 [DEBUG] [PaymentWatcher] Swap: 0d32395e25649caaaf54ea43244291f0f1039c3562468b3d31ab79614128e9ad: Calling paymentCallback
2022/08/24 15:38:24 [DEBUG] [FSM] event:id: 0d32395e25649caaaf54ea43244291f0f1039c3562468b3d31ab79614128e9ad, Event_OnClaimInvoicePaid on State_SwapInSender_AwaitClaimPayment
```

**Comment by grubles** [comment]
Can confirm shutting down LND during a swap does not produce a ton of spam in `~/.peerswap/log` and/or a ton of CPU usage like it did previously.

When shutting LND down, it seems there are multiple reconnect attempts in parallel though?

```
2022/08/24 19:56:41 [DEBUG] [grpc_conn]: grpc_retry attempt: 24, backoff for 30s
2022/08/24 19:56:41 [DEBUG] [grpc_conn]: grpc_retry attempt: 11, backoff for 30s
2022/08/24 19:56:41 [DEBUG] [grpc_conn]: grpc_retry attempt: 24, backoff for 30s
2022/08/24 19:56:41 [DEBUG] [grpc_conn]: grpc_retry attempt: 11, backoff for 30s
2022/08/24 19:56:41 [DEBUG] [grpc_conn]: grpc_retry attempt: 1, backoff for 30s
```

Restarting after some time allowed the LND node to proceed with a swap successfully.

**Comment by nepet** [comment]
@grubles the parallel attempts to retry are a result of several parallel streams that try to reconnect. This behavior is expected.

**Comment by wtogami** [comment]
iampigman in discord #development reports this caused LND to crash and peerswap didn't subsequently recover. Asked him for logs.

**Comment by wtogami** [comment]
The only reported failures were not caused by 117. It's time to merge because this is a substantial improvement and we need to build things on top of this.

**Comment by kornpow** [comment]
LGTM, no regressions with latest commit!

I still get a decent bit of spam upon reconnection about
`[PeerListener]: PEER_ONLINE`
`[PeerListener]: PEER_OFFLINE`
Most likely all for unrelated nodes to the swap.

But an improvement in this latest version, once the swap completes the spam stops.

**Comment by nepet** [comment]
Rebased onto master to resolve conflicting Makefiles.

**Pull request merged**
