### PR TITLE
delete the comment of old issue link

### PR DESCRIPTION
**Pull request by YusukeShimizu**
This comment seems to be about issue https://github.com/elementsproject/peerswap/issues/110, not https://github.com/elementsproject/peerswap/issues/109.  
https://github.com/elementsproject/peerswap/issues/110 is already closed, but I think the premium feature specifications have not been determined.

I think it would be better to reopen https://github.com/elementsproject/peerswap/issues/110 or create a separate issue for the premium feature.

If a separate issue is created, I'll re-modify the link to a new one.

### CODE REVIEW

**Comment by wtogami** [comment]
You're correct #109 was incorrect. But #110 I think is also incorrect. There's two separate components of the fee.

* The flat fee is prepayment for the requester to pay the onchain costs of the proposed swap.
*  The missing part is the premium which is a proportional fee for the requester to pay for opportunity cost of capital in (usually) buying incoming channel capacity.

**Comment by YusukeShimizu** [comment]
There seems to be missing part for onchain cost.
GetFlatSwapOutFee only seems to add the `opening-tx` costs.
What about a refund of the on-chain funds?(`claim_by_csv_tx`)

I assume the following pattern
* onchain costs
    * `opening-tx` and `claim_by_csv_tx`
* premium

**Comment by nepet** [comment]
@YusukeShimizu This seems to be correct.
As of now, we only take the `opening-tx` fee into account. We always tried to keep the trust overhead (fee-invoice) low and meet somewhere in the middle. We assume allowlisted peers to pay the invoice and claim the on-chain htlc, as they already committed themselves by paying the fee-invoice. 
The `opening-tx` on the other hand is always paid for by the party that broadcasts the tx so the swap fee as it is now covers the definite on-chain fee. 
Eventually we might switch to a deposit scheme where the `claim-by-csv-tx` is also covered to some extend, but where this part of the "fee" is returned via the on-chain tx if the initiator pays the invoice and claims by preimage.
Premium is on top of that and not security related.

I think you are right changing #109 to #110 in the comment, but the comment is somewhat misleading anyways. It should say something like: _Add premium once we have an idea on how to do that (mainly, how to negotiate it)_

**Comment by nepet** [comment]
By the way, this is an ancient comment that dates back to a time when we did not distinguish between premium and "upfront-fee" in terminology. You may consider removing the comment altogether.

**Pull request merged**
