### PR TITLE
Updated default regtest port to the correct port 18443.

### PR DESCRIPTION
**Pull request by cmdruid**
Default regtest port is incorrect. Should be 18443.

### CODE REVIEW

**Comment by wtogami** [comment]
@grubles please check if he's updating the correct port?

**Comment by wtogami** [comment]
OK so close not a bug?

**Comment by grubles** [comment]
No, @cmdruid is correct. The regtest port needs to be changed to 18443. Currently, it's 18332, which is what testnet uses.

**Comment by wtogami** [comment]
oops. OK. He needs to squash his commits to a single commit and put the main description in the first line of the commit.

**Review by wtogami — CHANGES_REQUESTED** [review]
Needs squash.
Please put "Updated default regtest port to the correct port 18443." on the first line of the commit message.

**Pull request closed without merging**
