### PR TITLE
Update dev dependencies

### LINKED ISSUE #177: nix-shell failing on mac
When I invoke the command `nix-shell` on Mac (MacOS Ventura 13.2.1) I get compilation errors around some `API_AVAILABLE`/`API_UNAVAILABLE` code. Does this mean anything to you? I can't figure out which part is not working.

Output attached in file [nix-shell-output.txt](https://github.com/ElementsProject/peerswap/files/10931493/nix-shell-output.txt)

### PR DESCRIPTION
**Pull request by nepet**
New updates:
* cln: `v23.02.2`
* bitcoind: `v24.0.1`

Was also built on `darwin x86_64`.

Resolves #177

### CODE REVIEW

**Comment by JssDWt** [comment]
Works for me on macOS 13.2.1 with nix-shell 2.13.3

**Comment by nepet** [comment]
@JssDWt did you run the tests? It seems that I am getting some apple framework related errors again :/.
Do you think it makes sense to drop the nix-shell dev environment in favor of a docker image that can build us the desired dependencies? This could also make it easier for us to test peerswap on upcoming versions and release candidates.

**Comment by JssDWt** [comment]
@nepet  No I didn't run the tests, will do.

I guess a docker would make sense if that makes testing things more platform independant. 

Do you have to clean the nix-shell build somehow btw? Sometimes it is completed instantly after witching branches.
This is the output then

```
bash: ./contrib/startup_regtest.sh: line 50: syntax error near unexpected token `else'
bash: ./contrib/startup_regtest.sh: line 50: `    else'
bash: setup_alias: command not found
```

**Comment by JssDWt** [comment]
Here's the ouput from `make test-integration`

```
go build -ldflags "-X main.GitCommit=3d3ac9dd3d73d789a991885955d4c178c8484b96" -tags "dev fast_test" -o ./out/test-builds/peerswapd ./cmd/peerswaplnd/peerswapd
# github.com/vulpemventures/go-secp256k1-zkp
In file included from ../../../go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1.go:12:
In file included from ../../../go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1-zkp/src/secp256k1.c:747:
../../../go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1-zkp/src/modules/surjection/main_impl.h:211:9: warning: comparison of nonnull parameter 'proof' not equal to a null pointer is 'true' on first encounter [-Wtautological-pointer-compare]
../../../go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1-zkp/include/secp256k1_surjectionproof.h:219:3: note: declared 'nonnull' here
../../../go/pkg/mod/github.com/vulpemventures/go-secp256k1-zkp@v1.1.5/secp256k1-zkp/include/secp256k1.h:153:54: note: expanded from macro 'SECP256K1_ARG_NONNULL'
# github.com/elementsproject/peerswap/cmd/peerswaplnd/peerswapd
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: framework not found Security
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [Makefile:65: out/test-builds/peerswapd] Error 2
```

**Comment by nepet** [comment]
Running `make test-bitcoin-cln` seems to work now on `darwin-x86_64`.

**Comment by nepet** [comment]
Nix pkgs still has `v0.15.5-beta` as most recent version. Going to update as soon as the packages have it.

**Pull request merged**
