### PR TITLE
gomod: Update to lnd v0.15.2-beta

### PR DESCRIPTION
**Pull request by nepet**
We need a fast update to the newest lnd version as there was a security issue detected.
https://github.com/lightningnetwork/lnd/issues/7002

As the bug was part of the btcd dependencies the fix applied in https://github.com/btcsuite/btcd/pull/1896 brings a long tail of dependency updates.

This commit updates the dependencies and adapts for all changes that are introduced by this new dependencies.

Please test this on bitcoin as well as on liquid-bitcoin as there have been some changes in the dependencies `go-elements` and `btcd`

### CODE REVIEW

**Comment by wtogami** [comment]
```
# git checkout origin/pr/142
HEAD is now at d88023c gomod: Update to lnd v0.15.2-beta
# make cln-release
# PeerSwap CLN builds
rm -f peerswap-plugin
rm -f out/peerswap-plugin
# peerswap-plugin binary is not installed in GOPATH because it must be called by full pathname as a CLN plugin.
# You may choose to install it to any location you wish.
go build -o peerswap-plugin -ldflags "-X main.GitCommit=d88023caabb3e45bf80f02016b3c84794c38c0d7" ./cmd/peerswap-plugin/main.go


go: github.com/lightningnetwork/lnd@v0.15.2-beta requires
	github.com/juju/testing@v0.0.0-20220203020004-a0ff61f03494 requires
	github.com/juju/utils/v3@v3.0.0-20220130232349-cd7ecef0e94a requires
	github.com/juju/testing@v0.0.0-20210302031854-2c7ee8570c07 requires
	github.com/juju/utils/v2@v2.0.0-20200923005554-4646bfea2ef1 requires
	launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
make: *** [Makefile:146: cln-release] Error 1

```

It got stuck for minutes then displayed this error.

**Comment by heelhook** [comment]
Tested ACK

**Review by heelhook — APPROVED** [review]
Tested ACK

**Comment by wtogami** [comment]
I'm still unable to fetch one of the dependencies. launchpad is rejecting my client for some reason. Any suggestions?

golang-1.19.1-1.fc37.x86_64

```
$ make cln-release
# PeerSwap CLN builds
rm -f peerswap-plugin
rm -f out/peerswap-plugin
# peerswap-plugin binary is not installed in GOPATH because it must be called by full pathname as a CLN plugin.
# You may choose to install it to any location you wish.
go build -o peerswap-plugin -ldflags "-X main.GitCommit=58a99117a22ef3cc9963c3692f7a138df137ce55" ./cmd/peerswap-plugin/main.go
go: github.com/lightningnetwork/lnd@v0.15.2-beta requires
	github.com/juju/testing@v0.0.0-20220203020004-a0ff61f03494 requires
	github.com/juju/utils/v3@v3.0.0-20220130232349-cd7ecef0e94a requires
	github.com/juju/testing@v0.0.0-20210302031854-2c7ee8570c07 requires
	github.com/juju/utils/v2@v2.0.0-20200923005554-4646bfea2ef1 requires
	launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
go: downloading github.com/btcsuite/btcd/btcutil v1.1.2
go: downloading github.com/elementsproject/glightning v0.0.0-20220713160855-49a9a8ec3e4d
go: downloading github.com/btcsuite/btcd v0.23.2
go: downloading github.com/vulpemventures/go-elements v0.4.0
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/jessevdk/go-flags v1.5.0
go: downloading github.com/btcsuite/btcd/btcec/v2 v2.2.1
go: downloading github.com/btcsuite/btcd/btcutil/psbt v1.1.5
go: downloading github.com/lightningnetwork/lnd v0.15.2-beta
go: downloading github.com/grpc-ecosystem/grpc-gateway/v2 v2.11.3
go: downloading google.golang.org/grpc v1.50.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading golang.org/x/sys v0.0.0-20221010160319-abe0a0adba9c
go: downloading golang.org/x/crypto v0.0.0-20221010152910-d6f0a8c073c2
go: downloading github.com/btcsuite/btcd/chaincfg/chainhash v1.0.1
go: downloading github.com/decred/dcrd/dcrec/secp256k1/v4 v4.1.0
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading golang.org/x/net v0.0.0-20221004154528-8021a29435af
go: downloading gopkg.in/macaroon-bakery.v2 v2.3.0
go: downloading github.com/go-errors/errors v1.4.2
go: downloading github.com/lightningnetwork/lnd/tor v1.1.0
go: downloading google.golang.org/genproto v0.0.0-20221010155953-15ba04fc1c0e
go: downloading github.com/btcsuite/btcwallet v0.16.1
go: downloading github.com/miekg/dns v1.1.50
go: downloading gopkg.in/macaroon.v2 v2.1.0
go: downloading github.com/decred/dcrd/lru v1.1.1
go: downloading github.com/stretchr/testify v1.8.0
go: downloading github.com/lightningnetwork/lightning-onion v1.2.0
go: downloading github.com/ltcsuite/ltcd v0.22.1-beta
go: downloading golang.org/x/term v0.0.0-20220919170432-7a66f970e087
go: github.com/lightningnetwork/lnd@v0.15.2-beta requires
	github.com/juju/testing@v0.0.0-20220203020004-a0ff61f03494 requires
	github.com/juju/utils/v3@v3.0.0-20220130232349-cd7ecef0e94a requires
	github.com/juju/testing@v0.0.0-20210302031854-2c7ee8570c07 requires
	github.com/juju/utils/v2@v2.0.0-20200923005554-4646bfea2ef1 requires
	launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
make: *** [Makefile:146: cln-release] Error 1
```

**Comment by wtogami** [comment]
https://twitter.com/wtogami/status/1580420954597240832
Figured out the build error. It requires `GOVCS='*:all'` and the `bzr` tool. LND should move to pure git deps. Those upstream repos had moved to git long ago.

The build problems were not peerswap's fault.

ACK

**Pull request merged**
