### PR TITLE
Rename peerswap-plugin

### PR DESCRIPTION
**Pull request by grubles**
This changes the name of the `peerswap-plugin` binary to `peerswap` and addresses #72.

### CODE REVIEW

**Comment by nepet** [comment]
It seems that the tests are still looking for the `peerswap-plugin` binary.

**Comment by grubles** [comment]
Looks like that fixed it.

**Comment by grubles** [comment]
@nepet This looks like it can be merged as well. Thoughts?

**Comment by nepet** [comment]
Had another look at the whole repo. We need some more renaming:
- `.gitignore` needs to ignore the `peerswap` binary (currently it ignores `peerswap-plugin`
- the `startup_regtest.sh` script in contrib still points to `peerswap-plugin`
- `setup_cln.md` has references to the `peerswap-plugin` binary
- also does `signetguide_cln`
- and also `upgrade.md`

Sorry for the late reply, I hope I found all the missing pieces that need to be renamed this time ^^.

**Review by nepet — APPROVED** [review]
Sgtm! :+1:

**Pull request merged**
