### PR TITLE
Update cln 0.11.0.1

### PR DESCRIPTION
**Pull request by nepet**
This PR updates cln to version 0.11.0.1 for tests and the development shell.

### CODE REVIEW

**Comment by wtogami** [comment]
```
FAIL: Test_LndCln_Bitcoin_SwapOut/claim_csv (32.08s)
```

Please look into this test failure. Re-ran it twice with the same result.

**Comment by sputn1ck** [comment]
> ```
> FAIL: Test_LndCln_Bitcoin_SwapOut/claim_csv (32.08s)
> ```
> 
> Please look into this test failure. Re-ran it twice with the same result.

Test runs locally on my end, gonna kick the ci again

**Comment by sputn1ck** [comment]
> > ```
> > FAIL: Test_LndCln_Bitcoin_SwapOut/claim_csv (32.08s)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please look into this test failure. Re-ran it twice with the same result.
> 
> Test runs locally on my end, gonna kick the ci again

Didn't update my nix-packages. Fails for me as well

**Comment by sputn1ck** [comment]
fixed it here:

https://github.com/sputn1ck/peerswap/commits/cln-0.11

@nepet can you rebase with these commits?

**Pull request merged**
