### PR TITLE
Add additional sanity checks before starting a swap

### PR DESCRIPTION
**Pull request by nepet**
We add an additional check that we can spend/receive the swap amount over the desired channel before initiating a swap.

### CODE REVIEW

**Comment by YusukeShimizu** [comment]
Since there are similarities with `CheckChannel` function, I think it would be good if `CheckChannel` could be eliminated and integrated into checks using `SpendableMsat`.

The following may be the scope of https://github.com/ElementsProject/peerswap/issues/81, but I mention it because I am thinking of working on it.

I think it would be nice to be able to check `htlc_maximum_msat` as well.
it would be nice to check `SpendableMsat` after we received the swap_out_agreement that contains the "fee_invoice". 

I would appreciate your feedback.

**Comment by wtogami** [comment]
Is it common for LND nodes to adjust `htlc_maximum_msat` dynamically?

**Comment by nepet** [comment]
> Since there are similarities with `CheckChannel` function, I think it would be good if `CheckChannel` could be eliminated and integrated into checks using `SpendableMsat`.

True, there is indeed some room for refactoring and improvement. I will refactor said methods and the interface once I know that the pr fixes @grubles problem with the swap amounts.

> The following may be the scope of #81, but I mention it because I am working on it.
> 
> I think it would be nice to be able to check `htlc_maximum_msat` as well.

We can only ever give an estimate on what is spendable. For cln we can use `spendable_msat` if it is set. Otherwise we have to deal with a fallback. It is definitely a good idea to check `htlc_maximum_msat` as long as we don't split the payment.

> it would be nice to check `SpendableMsat` after we received the swap_out_agreement that contains the "fee_invoice".

I would rather check before we start the swap at all, once we are at the point where we want to pay an invoice we can just do so and act accordingly if it fails.

**Comment by nepet** [comment]
Oh sorry, maybe I misunderstood, of course it would be nice to check if we can pay the `whole` swap amount before paying the `fee_invoice` ^^

**Comment by YusukeShimizu** [comment]
> I will refactor said methods and the interface once I know that the pr fixes @grubles problem with the swap amounts.

I understood.
LGTM

> it would be nice to check if we can pay the whole swap amount before paying the fee_invoice 

Yes, this is what I wanted to tell you.

I will implement it as a response to https://github.com/ElementsProject/peerswap/issues/81.

**Comment by wtogami** [comment]
This PR seems to do the right thing.

> I will refactor said methods and the interface once I know that the pr fixes @grubles problem with the swap amounts.

Here it sounds that Peter will refactor to check `htlc_maximum_msat`.

> I will implement it as a response to https://github.com/ElementsProject/peerswap/issues/81.

But Yusuke said he can implement it after this is merged.

Let's merge this now since it works then you two discuss who takes the next step?

**Comment by nepet** [comment]
Let me clean this up a bit so that we can merge it as is (without `htlc_maximum_msat`). I am happy to pass this to @YusukeShimizu for further steps.

Is this okay for you @YusukeShimizu, @wtogami?

**Comment by YusukeShimizu** [comment]
Yes, I am OK.

I will implement the following two features.
1. check if we can pay the whole swap amount before paying the fee_invoice
2. make htlc_maximum_msat be taken into account when calculating SpendableMsat

**Comment by wtogami** [comment]
https://github.com/ElementsProject/peerswap/actions/runs/6177482756/job/16768697864?pr=235
Test failure

**Comment by grubles** [comment]
Unpatched CLN node impossible swap-out is rejected by remote patched LND peer. Impossible swap-in is rejected locally.

```
{                                                                                                                                                                                                                  
   "code": -1,                                                                                                                                                                                                     
   "message": "swap canceled, reason: from the LND peer: exceeding receivable amount_msat: 236942513000"                                                                                                           
} 
```

**Comment by grubles** [comment]
Don't merge yet. I want to test a little bit more with different configurations (a CLN <> CLN channel and a LND <> LND channel).

**Comment by grubles** [comment]
Successfully tested with two LND nodes (one unpatched, one patched).

**Pull request merged**
