### PR TITLE
Fix stuck recovery

### PR DESCRIPTION
**Pull request by nepet**
Swaps that have been claimed by csv can get stuck on the peers side on startup.
This PR reworks the tx watcher to check all blocks for the desired tx since the block the swap started. If the tx is above the safety limit we return an error and fail the swap.

Fixes: #214

### CODE REVIEW

**Comment by nepet** [comment]
Please have a detailed look at and double check the `observationLoop` and the `IsTxInMempoolOrRange` method during review.

**Comment by wtogami** [comment]
Blockstream Store is now running 63378ba8fff94052383f25d3dddcea04157cd870. Unfortunately this doesn't seem to have helped to unstick that swap.

### Before 
      {
         "id": "975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd",
         "created_at": 1690593684,
         "asset": "lbtc",
         "type": "swap-in",
         "role": "receiver",
         "state": "State_SwapInReceiver_AwaitTxConfirmation",
         "initiator_node_id": "02d0e03736cbfc73f3c005bc3770327df0e84bd69bc8e557c279887344deb8bce2",
         "peer_node_id": "02d0e03736cbfc73f3c005bc3770327df0e84bd69bc8e557c279887344deb8bce2",
         "amount": 8000000,
         "channel_id": "798627x1031x0",
         "opening_tx_id": "9af850fd41bf916146f6bf43c4da4551c69ed9d3473ab61ff52eb381fd0465ae",
         "lnd_chan_id": 878099672823431168
      },

### Log during startup
Aug 06 23:25:16 lightning-charge-production-hwwp docker[92511]: 2023-08-06T23:25:16.004Z INFO    plugin-peerswap: [Swap:4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f]: Recovering from state State_SwapOutReceiver_SendTxBroadcastedMessage
Aug 06 23:25:16 lightning-charge-production-hwwp docker[92511]: 2023-08-06T23:25:16.008Z DEBUG   plugin-peerswap: [FSM] event:id: 4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f, Event_ActionFailed on State_SwapOutReceiver_SendTxBroadcastedMessage

### After
      {
         "id": "975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd",
         "created_at": 1690593684,
         "asset": "lbtc",
         "type": "swap-in",
         "role": "receiver",
         "state": "State_SwapInReceiver_AwaitTxConfirmation",
         "initiator_node_id": "02d0e03736cbfc73f3c005bc3770327df0e84bd69bc8e557c279887344deb8bce2",
         "peer_node_id": "02d0e03736cbfc73f3c005bc3770327df0e84bd69bc8e557c279887344deb8bce2",
         "amount": 8000000,
         "channel_id": "798627x1031x0",
         "opening_tx_id": "9af850fd41bf916146f6bf43c4da4551c69ed9d3473ab61ff52eb381fd0465ae",
         "lnd_chan_id": 878099672823431168
      },

**Comment by nepet** [comment]
Ok some thoughts:

for `975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd`:
- Starting Blockheight is `2447093`
- `opening_tx_id=cf6edaa5f0240d652155c9921298922e8b97c8b117ce941dc4d18a60e1b6c523`
- `opening_tx` was confirmed the first time in block `2447094`
- `opening_tx` was spent in block `2447154`
- difference is 60 blocks, so `csv` worked out in the end.

https://github.com/ElementsProject/peerswap/blob/63378ba8fff94052383f25d3dddcea04157cd870/swap/actions.go#L657-L671

These lines from the `AwaitTxConfirmationAction` alone should cancel the ongoing swap, which would be intended behavior. The following test passes:

https://github.com/ElementsProject/peerswap/blob/63378ba8fff94052383f25d3dddcea04157cd870/test/recovery_test.go#L218-L234

We basically create a situation in which the csv limit passes and where the maker refunds itself. Restarting the taker node calls the recovery and cancels the ongoing swap that now exceeded the limits.

On the other hand we have `4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f` where we are stuck in the state `State_SwapOutReceiver_SendTxBroadcastedMessage` which is not covered yet by this PR.

I suspect that `4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f` being created earlier and/or having an Id of a lesser lexicographic order is the first we try to recover, but fail, as we do not have proper recovery for this state yet.
It seems that the recovery mechanism of the state machine works sequentially and returns on the first encountered error, leaving the other swaps untouched.

Give me some time to fix this on the state machine, that should be able to recover from `975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd` as well as from `4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f`, and that does not exit on error and continues to recover the next swap.

**Comment by grubles** [comment]
Tested using signet L-BTC swaps since the BTC timeouts would take a while (about 3 days):

Ordinary swap-ins work.

Turning off PeerSwap on the remote peer and then starting it back up immediately results in `State_ClaimedPreimage`.

When turning off PeerSwap on the remote peer after 50% of the CSV timeout has passed, the result is `State_ClaimedCoop, exceeded safe swap range`.

**Comment by wtogami** [comment]
This is a huge improvement! Blockstream Store PeerSwap is restored.

`4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f` remains stuck like above but it no longer prevents other recoveries to happen. `975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd` successfully recovers with the expected Coop state.

New problem ...
### While elementsd is stopped
```
2023-08-11T07:12:47.175Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:47.175Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:48.175Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:48.175Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:49.177Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:49.177Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
2023-08-11T07:12:50.175Z DEBUG   plugin-peerswap: block watcher: Post \"http://127.0.0.1:7041/wallet/peerswap\": dial tcp 127.0.0.1:7041: connect: connection refused
```

## elementsd restarted into different cookie
```
2023-08-11T07:13:12.677Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:13.425Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:13.676Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:14.425Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:14.676Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:15.426Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:15.677Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
2023-08-11T07:13:16.425Z DEBUG   plugin-peerswap: block watcher: Authorization failed: Incorrect user or password
```

This latter problem is the same as https://github.com/ElementsProject/peerswap/issues/17 where we don't self-recover by reading the new cookie file. It will go forever.

New problem: Retry is far too fast, overwhelming the log storage.
For now slow down the retry?

**Comment by nepet** [comment]
We can slow it down, it tries once a second as liquid is really fast :rocket: but I guess it would not hurt to try once every 30 sec or 1min.

**Comment by wtogami** [comment]
`2023-08-11T06:02:56.570Z DEBUG   plugin-peerswap: Waiting for all open swaps to recover.`
This might be better as `INFO`?

**Comment by wtogami** [comment]
### Not a regression but think about this for later

If CLN and peerswap start at the same time there is no guarantee that these peers will be connected before these recoveries begin. Aren't these recoveries more likely to have a better outcome if the peer is connected at that moment? Is `Waiting for cln to be synced...` waiting for 4.6 seconds long enough? My guess is no.

In the below log you see `plugin-peerswap` restarted during the already running CLN. You see incoming polling at random times interspersed during the recovery messages which makes me suspect we are not waiting long enough before attempting the recoveries.

```
2023-08-11T06:02:44.891Z INFO    plugin-peerswap: Using core-lightning version v23.05.2
2023-08-11T06:02:44.891Z INFO    plugin-peerswap: Waiting for cln to be synced...
2023-08-11T06:02:55.114Z INFO    plugin-peerswap: Cln synced, continue...
... snip ...
2023-08-11T06:02:56.505Z INFO    plugin-peerswap: suspicious_peers: []
2023-08-11T06:02:56.505Z INFO    plugin-peerswap:
2023-08-11T06:02:56.569Z INFO    plugin-peerswap: [Swap:4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f]: Recovering from state State_SwapOutReceiver_SendTxBroadcastedMessage
2023-08-11T06:02:56.570Z DEBUG   plugin-peerswap: Waiting for all open swaps to recover.
2023-08-11T06:02:56.571Z INFO    plugin-peerswap: [Swap:70b00d81453a1a441904de2e51fb51f52a34d928ed2327766210b43f1e5bcfd0]: Recovering from state State_SwapInReceiver_AwaitTxConfirmation
2023-08-11T06:02:56.571Z INFO    plugin-peerswap: [Swap:975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd]: Recovering from state State_SwapInReceiver_AwaitTxConfirmation
2023-08-11T06:02:56.571Z INFO    plugin-peerswap: [Swap:ca17bae36e72c7348887e1d4c834ee0a9475a65ec22fbabb423b6cf841e3182a]: Recovering from state State_SwapOutReceiver_SendTxBroadcastedMessage
2023-08-11T06:02:56.571Z DEBUG   plugin-peerswap: [RedundantSender] start sending messages of type 42077 to 0360a41eb8c3fe09782ef6c984acbb003b0e1ebc4fe10ae01bab0e80d76618c8f4
2023-08-11T06:02:56.578Z DEBUG   plugin-peerswap: [FSM] event:id: 4d1b7d6f1dd4de3e93132d6b8c489829f52a277e5aedf699830040a025eef14f, Event_ActionFailed on State_SwapOutReceiver_SendTxBroadcastedMessage
2023-08-11T06:02:56.586Z DEBUG   plugin-peerswap: [FSM] event:id: ca17bae36e72c7348887e1d4c834ee0a9475a65ec22fbabb423b6cf841e3182a, Event_ActionSucceeded on State_SwapOutReceiver_SendTxBroadcastedMessage
2023-08-11T06:02:56.627Z DEBUG   plugin-peerswap: Received poll from peer 029a0f8111f0bcb94003413838451dfc1d0faed030ef46ff84d96c0dc5be3d1415: {\"version\":3,\"assets\":[\"btc\",\"lbtc\"],\"peer_allowed\":true}
2023-08-11T06:02:56.681Z DEBUG   plugin-peerswap: Received poll from peer 03a465772d45616bf6c8450a69191db8f3cf8cca19ff92138735fd5f1d436fe4dc: {\"version\":3,\"assets\":[\"lbtc\",\"btc\"],\"peer_allowed\":true}
2023-08-11T06:02:56.711Z DEBUG   plugin-peerswap: [FSM] event:id: 975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd, Event_ActionFailed on State_SwapInReceiver_AwaitTxConfirmation
2023-08-11T06:02:56.714Z DEBUG   plugin-peerswap: [FSM] event:id: 975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd, Event_ActionSucceeded on State_SwapInReceiver_SendPrivkey
2023-08-11T06:02:56.715Z DEBUG   plugin-peerswap: Received poll from peer 035b1ff29e8db1ba8f2a4f4f95db239b54069cb949b8cde329418e2a83da4f1b30: {\"version\":3,\"assets\":[\"btc\",\"lbtc\"],\"peer_allowed\":true}
2023-08-11T06:02:56.718Z DEBUG   plugin-peerswap: [FSM] event:id: 975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd, Event_ActionSucceeded on State_SwapInReceiver_SendCoopClose
2023-08-11T06:02:56.718Z INFO    plugin-peerswap: [Swap:975ca468baf5dc8843afc61acb99e567b615f9fc123af250d5541eb591fe60dd] Swap claimed cooperatively
2023-08-11T06:02:56.727Z DEBUG   plugin-peerswap: Received poll from peer 039cdd937f8d83fb2f78c8d7ddc92ae28c9dbb5c4827181cfc80df60dee1b7bf19: {\"version\":3,\"assets\":[\"btc\",\"lbtc\"],\"peer_allowed\":true}
2023-08-11T06:02:56.750Z INFO    plugin-peerswap: [TxWatcher] checkTxAboveCsvHeight returned: empty gettxout response
2023-08-11T06:02:56.757Z DEBUG   plugin-peerswap: [FSM] event:id: 70b00d81453a1a441904de2e51fb51f52a34d928ed2327766210b43f1e5bcfd0, Event_ActionFailed on State_SwapInReceiver_AwaitTxConfirmation
2023-08-11T06:02:56.760Z DEBUG   plugin-peerswap: [FSM] event:id: 70b00d81453a1a441904de2e51fb51f52a34d928ed2327766210b43f1e5bcfd0, Event_ActionSucceeded on State_SwapInReceiver_SendPrivkey
2023-08-11T06:02:56.762Z DEBUG   plugin-peerswap: [FSM] event:id: ca17bae36e72c7348887e1d4c834ee0a9475a65ec22fbabb423b6cf841e3182a, Event_OnClaimInvoicePaid on State_SwapOutReceiver_AwaitClaimInvoicePayment
2023-08-11T06:02:56.762Z INFO    plugin-peerswap: [Swap:ca17bae36e72c7348887e1d4c834ee0a9475a65ec22fbabb423b6cf841e3182a] Swap claimed with preimage 0b3d604b5364ae6dadfb33e08a56fc819c873e342efaa38681bd0360e2136000
2023-08-11T06:02:56.762Z DEBUG   plugin-peerswap: [RedundantSender] stop sending messages of type 42077 to 0360a41eb8c3fe09782ef6c984acbb003b0e1ebc4fe10ae01bab0e80d76618c8f4
2023-08-11T06:02:56.764Z DEBUG   plugin-peerswap: [FSM] event:id: 70b00d81453a1a441904de2e51fb51f52a34d928ed2327766210b43f1e5bcfd0, Event_ActionSucceeded on State_SwapInReceiver_SendCoopClose
2023-08-11T06:02:56.764Z INFO    plugin-peerswap: [Swap:70b00d81453a1a441904de2e51fb51f52a34d928ed2327766210b43f1e5bcfd0] Swap claimed cooperatively
2023-08-11T06:02:57.033Z DEBUG   plugin-peerswap: Received poll from peer 03c53ba23ea401b185a9d6e79b3ba776d4e78ab1a90e8ca28de90da27494002a12: {\"version\":3,\"assets\":[\"lbtc\",\"btc\"],\"peer_allowed\":true}
```

**Comment by wtogami** [comment]
> Is `Waiting for cln to be synced...` waiting for 11 seconds long enough? My guess is no.

There is no guarantee that any length of time will be long enough for peers to reconnect. However judging from the timing of those incoming polls for already-connected peers I think we would be better off waiting 10 seconds after `Cln synced, continue...` before proceeding with recoveries. That gives a high chance of a live peer reconnecting before recoveries without being too long for the vast majority of times we aren't waiting for recoveries.

**Alternative**: How easily can we detect if we have any pending recoveries? If we have none then we have no reason to wait during peerswap startup. `Waiting for all open swaps to recover.` could then conditionally instead print `No pending swaps to recover.`

**Comment by wtogami** [comment]
Please rename `Waiting for all open swaps to recover.` to `Waiting for all pending swaps to recover.`

**Comment by wtogami** [comment]
ACK, merging now because this is a strict improvement and we need other pull requests on top of this.
Fix minor comments in separate ticket.

**Pull request merged**
